### ISSUE TITLE
RITE Ingestion Ignores Special Character Errors

### ISSUE THREAD

**Issue by pauls4GE** [ge-high-assurance/RITE#20] opened 2023-03-16 00:25 UTC
**Background**:
RITE Ingestion Ignores Special Character Errors

**Acceptance Criteria**:

**Implementation Details**:

**Test Data**:

**Comment by baoluomeng** [comment] 2023-03-16 14:54
Was this caused by ingesting using the manifest file or the new functionality "upload as ingestion package"?

**Comment by chrisage** [comment] 2023-07-25 18:32
@pauls4GE Can you provide a test case example (and expected vs actual results)?

**Comment by pauls4GE** [comment] 2023-07-26 14:13
Is this only limited to special characters in Owl files or even in CSVs?

**Comment by saratge** [comment] 2023-08-03 05:42
@pauls4GE we encountered this in the FAA project where the SADL files and their subsequent translation into OWL had special chars

**Comment by saratge** [comment] 2023-08-21 05:54
Does not seem to fail if the special char is within Ontology, but fails same character within  instance data csv 
![image](https://github.com/ge-high-assurance/RITE/assets/98990225/37d56070-134d-475a-8184-98046742917d)



Sample CSV:
description,identifier,title,definedIn_identifier,actedOnBehalfOf_identifier,dataInsertedBy_identifier
,SC-205,,�,,
,RTCA,,,,

**Comment by saratge** [comment] 2023-08-22 02:20
It is okay to fail with � which is un-renderable and hence is displayed in that fashion.
However, instance data with special characters such as greek alphabet has no problems during ingestion but returns a question mark when executing query nodegroups. 
Closing this issue as it is SemTK/RACK related 
See: https://github.com/ge-high-assurance/RACK/issues/994 for more information

**Closed** 2023-08-22 02:20 UTC
Labels: bug, question, medium-priority
