### ISSUE TITLE
Error on upload of ingestion package

### ISSUE THREAD

**Issue by davidcok** [ge-high-assurance/RITE#110] opened 2023-08-18 15:17 UTC
Extracting bug report from https://github.com/ge-high-assurance/RITE/pull/95 

Testing done with [this package](https://github.com/ge-high-assurance/RITE/tree/main/examples/ingestion-packages/OEM-Ingestion-Package)

Save ingestion package as zip works fine, however, upload as ingestion package throws this error (Manifest import ingests successfully though, so it is not an issue with the package):

Image taken from https://github.com/ge-high-assurance/RITE/pull/95
![](https://user-images.githubusercontent.com/66636651/261020162-4b06e75c-f0fc-4b0d-b64c-c0cbd97c193d.png)

**Comment by saratge** [comment] 2023-08-28 23:55
@davidcok  I am unable to reproduce the issue on the main branch, closing
Both manifest import and upload as ingestion package succeed, with the same number of triples on each datagraph

**Closed by saratge** 2023-08-28 23:55 UTC
